#!/bin/bash

DOCKER_REGISTRY=${DOCKER_REGISTRY:-}
DOCKER_IMG=${DOCKER_IMG:-flask_sample}
DOCKER_TAG=${DOCKER_TAG:-0.1}

docker build -t $DOCKER_REGISTRY$DOCKER_IMG:$DOCKER_TAG .
#docker push $DOCKER_REGISTRY$DOCKER_IMG:$DOCKER_TAG